name: Build ExpressLRS Repartitioner
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.target }}

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pip install wheel

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio

    - name: Run PlatformIO
      run: |
        platformio platform update
        platformio platform install native
        mkdir -p ~/artifacts
        pio run
        mv .pio/build/esp32dev/firmware.bin ~/artifacts/repartitioner.bin

    - name: Store Artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: repartitioner-${{ env.GITHUB_REF_SLUG_URL }}-${{ github.run_number }}
        path: ~/artifacts/*.bin
      continue-on-error: true
